import type { Blueprint } from '@madori/lib/blueprints/types.js'
import type { GeneratedFile, GraphQLSDKGeneratorInterface } from './generation-pipeline.js'
import { toPascalCaseEntry } from './type-generator.js'

/**
 * Converts a kebab-case or lowercase handle to PascalCase (without "Entry" suffix).
 * Examples: "blog" → "Blog", "getting-started" → "GettingStarted"
 */
function toPascalCase(handle: string): string {
  return handle
    .split(/[-_]/)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('')
}

/**
 * GraphQLSDKGenerator produces typed GraphQL operation files, a client module,
 * and a barrel file for each collection blueprint.
 *
 * Generated operations assume a GraphQL API following Madori conventions:
 * - `{handle}Entry(slug: String!): {Type}` for single entry lookup
 * - `{handle}Entries(options: ListOptions): [{Type}]` for listing
 */
export class GraphQLSDKGenerator implements GraphQLSDKGeneratorInterface {
  /**
   * Generate all GraphQL SDK files from blueprints.
   * Returns client.ts, per-collection operation files, and index.ts barrel.
   */
  async generate(blueprints: Blueprint[]): Promise<GeneratedFile[]> {
    if (blueprints.length === 0) {
      return []
    }

    const files: GeneratedFile[] = []

    // 1. Generate graphql/client.ts
    files.push(this.generateClient())

    // 2. Generate per-collection operation files
    for (const blueprint of blueprints) {
      files.push(this.generateOperations(blueprint))
    }

    // 3. Generate graphql/index.ts barrel
    files.push(this.generateBarrel(blueprints))

    return files
  }

  /**
   * Generate the graphql/client.ts module with endpoint config and typed request function.
   */
  generateClient(): GeneratedFile {
    const content = `/**
 * GraphQL client with typed request function.
 * Auto-generated by Madori CLI — do not edit manually.
 */

export type TypedDocumentNode<TResult, TVariables> = {
  __apiType?: (variables: TVariables) => TResult
  kind: string
  definitions: unknown[]
}

export interface GraphQLClientConfig {
  endpoint: string
  headers?: Record<string, string>
}

const defaultConfig: GraphQLClientConfig = {
  endpoint: '/api/graphql',
}

let config: GraphQLClientConfig = { ...defaultConfig }

export function configureGraphQL(options: Partial<GraphQLClientConfig>): void {
  config = { ...config, ...options }
}

export async function request<TResult, TVariables extends Record<string, unknown>>(
  document: TypedDocumentNode<TResult, TVariables>,
  variables?: TVariables
): Promise<TResult> {
  const response = await fetch(config.endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...config.headers },
    body: JSON.stringify({ query: (document as any).loc?.source?.body ?? String(document), variables }),
  })
  const json = await response.json()
  if (json.errors) throw new Error(json.errors[0].message)
  return json.data
}
`

    return {
      filename: 'graphql/client.ts',
      content,
    }
  }

  /**
   * Generate a per-collection operations file with TypedDocumentNode exports
   * and typed get/list functions.
   */
  generateOperations(blueprint: Blueprint): GeneratedFile {
    const handle = blueprint.handle
    const pascalCase = toPascalCase(handle)
    const typeName = toPascalCaseEntry(handle)

    const getDocName = `Get${pascalCase}EntryDocument`
    const listDocName = `List${pascalCase}EntriesDocument`
    const getFnName = `get${pascalCase}Entry`
    const listFnName = `list${pascalCase}Entries`

    const content = `/**
 * GraphQL operations for the "${handle}" collection.
 * Auto-generated by Madori CLI — do not edit manually.
 */

import type { ${typeName} } from '../types/${handle}.js'
import type { TypedDocumentNode } from './client.js'
import { request } from './client.js'

export interface ListOptions {
  limit?: number
  offset?: number
  sort?: string
  order?: 'asc' | 'desc'
}

// --- Query document nodes ---

export const ${getDocName} = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: '${getFnName}' },
      variableDefinitions: [
        {
          kind: 'VariableDefinition',
          variable: { kind: 'Variable', name: { kind: 'Name', value: 'slug' } },
          type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
        },
      ],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: '${handle}Entry' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'slug' },
                value: { kind: 'Variable', name: { kind: 'Name', value: 'slug' } },
              },
            ],
          },
        ],
      },
    },
  ],
} as unknown as TypedDocumentNode<{ ${handle}Entry: ${typeName} | null }, { slug: string }>

export const ${listDocName} = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: '${listFnName}' },
      variableDefinitions: [
        {
          kind: 'VariableDefinition',
          variable: { kind: 'Variable', name: { kind: 'Name', value: 'options' } },
          type: { kind: 'NamedType', name: { kind: 'Name', value: 'ListOptions' } },
        },
      ],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: '${handle}Entries' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'options' },
                value: { kind: 'Variable', name: { kind: 'Name', value: 'options' } },
              },
            ],
          },
        ],
      },
    },
  ],
} as unknown as TypedDocumentNode<{ ${handle}Entries: ${typeName}[] }, { options?: ListOptions }>

// --- Operation functions ---

export async function ${getFnName}(slug: string): Promise<${typeName} | null> {
  const result = await request(${getDocName}, { slug })
  return result.${handle}Entry
}

export async function ${listFnName}(options?: ListOptions): Promise<${typeName}[]> {
  const result = await request(${listDocName}, { options })
  return result.${handle}Entries
}
`

    return {
      filename: `graphql/${handle}-operations.ts`,
      content,
      blueprintHandle: handle,
    }
  }

  /**
   * Generate the graphql/index.ts barrel that re-exports client and all operation files.
   */
  generateBarrel(blueprints: Blueprint[]): GeneratedFile {
    const lines = ["export * from './client.js'"]

    for (const blueprint of blueprints) {
      lines.push(`export * from './${blueprint.handle}-operations.js'`)
    }

    return {
      filename: 'graphql/index.ts',
      content: lines.join('\n') + '\n',
    }
  }
}
